# Generated by Django 4.1.4 on 2023-07-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_alter_post_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_or_video_content',
            new_name='image',
        ),
    ]
